keys:
  - &alex age19mwwlwnwfaaakuctmmrjzuhjnvm6vvn9urgc0ec9gwjf7e8lrews0rksk4
  - &evo age1fhz3gpf69k2z38krv07ygn5wvv8wppcuqqppqdnlw0sej5acxq8scd62tk

creation_rules:
  - path_regex: secrets/common\.yaml$
    age:
      - *alex
      - *evo
  - path_regex: secrets/evo-nixos\.yaml$
    age:
      - *alex
      - *evo
  - path_regex: secrets/pad-nixos\.yaml$
    age:
      - *alex
  - path_regex: secrets/vps-nixos\.yaml$
    age:
      - *alex
