{
  config,
  lib,
  pkgs,
  ...
}: let
  piWebAccessRoot = "${pkgs.pi-web-access}/share/pi-web-access";
  llmWikiRoot = "${pkgs.llm-wiki}/share/llm-wiki";
  llmWikiDir = "${config.home.homeDirectory}/Sync/llm-wiki";

  starterConfig = builtins.toJSON {
    provider = "exa";
    workflow = "summary-review";
    curatorTimeoutSeconds = 20;
    githubClone = {
      enabled = true;
      maxRepoSizeMB = 350;
      cloneTimeoutSeconds = 30;
      clonePath = "/tmp/pi-github-repos";
    };
    youtube = {
      enabled = true;
      preferredModel = "gemini-3-flash-preview";
    };
    video = {
      enabled = true;
      preferredModel = "gemini-3-flash-preview";
      maxSizeMB = 50;
    };
    shortcuts = {
      curate = "ctrl+shift+s";
      activity = "ctrl+shift+w";
    };
  };

  llmWikiReadme = pkgs.writeText "llm-wiki-README.md" ''
    # llm-wiki

    This wiki is shared through Syncthing at `~/Sync/llm-wiki`.
    You can open this folder directly in Obsidian as a vault.

    ## Recommended structure

    PARA folders:

    - `pages/projects/`
    - `pages/areas/`
    - `pages/resources/`
    - `pages/archives/`

    Other useful folders:

    - `pages/sources/` for captured source material generated by the tools
    - `pages/journal/daily/` for journal entries
    - `templates/obsidian/` for reusable Obsidian templates

    Quick convenience folders are also allowed:

    - `pages/technical/`
    - `pages/personal/`

    ## Metadata conventions

    - use `domain: technical` or `domain: personal`
    - use `areas: [...]` for long-lived themes and responsibilities
    - use `hosts: [...]` for host-specific knowledge

    If `hosts` is omitted, knowledge is treated as global.
  '';

  llmWikiSchema = pkgs.writeText "llm-wiki-WIKI_SCHEMA.md" ''
    # llm-wiki schema

    ## Recommendation

    Prefer **one wiki root** with:

    - domain-level metadata for `technical` vs `personal`
    - PARA-style folders for storage and browsing
    - journal notes under `pages/journal/daily/`

    This keeps search, memory digests, cross-links, and Syncthing simple.

    ## Canonical page frontmatter

    ```yaml
    ---
    type: concept | entity | synthesis | analysis | evolution | procedure | decision | identity
    title: Example Title
    aliases: []
    tags: [nixos, pi]
    hosts: []
    domain: technical
    areas: [infrastructure, ai]
    status: active
    updated: 2026-04-19
    source_ids: []
    summary: One-line summary
    ---
    ```

    ## Journal page frontmatter

    ```yaml
    ---
    type: journal
    title: 2026-04-19 Daily Journal
    aliases: []
    tags: [journal, reflection]
    hosts: []
    domain: personal
    areas: [journal]
    status: active
    updated: 2026-04-19
    summary: One-line summary of the day
    ---
    ```

    ## Host-specific example

    ```yaml
    hosts:
      - pad-nixos
    ```

    ## Folder examples

    - `pages/resources/technical/`
    - `pages/areas/personal/`
    - `pages/projects/technical/`
    - `pages/journal/daily/`
    - `pages/technical/` and `pages/personal/` for simpler direct separation
  '';

  llmWikiTechnicalStarter = pkgs.writeText "llm-wiki-system-landscape.md" ''
    ---
    type: concept
    title: System Landscape
    aliases: []
    tags:
      - nixos
      - pi
      - para
    hosts: []
    domain: technical
    areas:
      - infrastructure
      - ai
    status: active
    updated: 2026-04-19
    source_ids: []
    summary: High-level overview of the shared technical environment.
    ---
    # System Landscape

    ## Current understanding

    - This wiki root is shared across devices through Syncthing.
    - The vault can be edited directly from Obsidian.
    - Technical knowledge should usually use `domain: technical`.
    - PARA folders help separate projects, areas, resources, and archives.
    - Host-specific notes should use the `hosts:` field.

    ## Evidence

    - The repository exports `PI_LLM_WIKI_DIR=~/Sync/llm-wiki`.
    - The llm-wiki extension filters host-specific pages by the current hostname.

    ## Tensions / caveats

    - Some technical preferences are global, while others are host-specific.
    - Folder structure and frontmatter should reinforce each other.

    ## Open questions

    - Which technical notes belong in projects vs areas vs resources?
    - Which topics deserve dedicated area pages?

    ## Related pages

    - [[resources/technical/pad-nixos|pad-nixos]]
    - [[areas/personal/personal-identity|Personal Identity]]
  '';

  llmWikiPadStarter = pkgs.writeText "llm-wiki-pad-nixos.md" ''
    ---
    type: entity
    title: pad-nixos
    aliases: []
    tags:
      - host
      - laptop
    hosts:
      - pad-nixos
    domain: technical
    areas:
      - infrastructure
      - laptop
    status: active
    updated: 2026-04-19
    source_ids: []
    summary: Laptop-specific notes and constraints.
    ---
    # pad-nixos

    ## Current understanding

    - This page is visible primarily when the current host is `pad-nixos`.
    - Use this pattern for device-specific hardware, workflows, and quirks.

    ## Evidence

    - The page frontmatter sets `hosts: [pad-nixos]`.

    ## Tensions / caveats

    - Avoid putting globally relevant knowledge here.

    ## Open questions

    - Which laptop-only workflows should live here versus in global technical pages?

    ## Related pages

    - [[resources/technical/system-landscape|System Landscape]]
  '';

  llmWikiPersonalStarter = pkgs.writeText "llm-wiki-personal-identity.md" ''
    ---
    type: identity
    title: Personal Identity
    aliases: []
    tags:
      - identity
      - personal
    hosts: []
    domain: personal
    areas:
      - identity
      - life-ops
    status: active
    updated: 2026-04-19
    source_ids: []
    summary: Stable user-level preferences, values, and working style.
    ---
    # Personal Identity

    ## Current understanding

    - This section is for durable user preferences and identity-level notes.
    - It is distinct from system-specific technical knowledge.
    - Obsidian can be used for direct manual contribution here.

    ## Evidence

    - Personal preferences often apply across all hosts and sessions.

    ## Tensions / caveats

    - Keep transient task notes elsewhere.
    - Keep machine-specific operational detail in technical pages.

    ## Open questions

    - Which preferences are stable enough to belong here?

    ## Related pages

    - [[resources/technical/system-landscape|System Landscape]]
  '';

  llmWikiDailyJournalTemplate = pkgs.writeText "llm-wiki-daily-journal.md" ''
    ---
    type: journal
    title: {{date:YYYY-MM-DD}} Daily Journal
    aliases: []
    tags:
      - journal
      - reflection
    hosts: []
    domain: personal
    areas:
      - journal
    status: active
    updated: {{date:YYYY-MM-DD}}
    summary: Daily notes and reflection
    ---
    # {{date:YYYY-MM-DD}} Daily Journal

    ## Focus

    -

    ## Notes

    -

    ## Wins

    -

    ## Friction

    -

    ## Follow-ups

    -
  '';

  llmWikiPageTemplate = pkgs.writeText "llm-wiki-page-template.md" ''
    ---
    type: concept
    title: New Page
    aliases: []
    tags: []
    hosts: []
    domain: technical
    areas: []
    status: draft
    updated: {{date:YYYY-MM-DD}}
    source_ids: []
    summary: One-line summary
    ---
    # New Page

    <!-- Rename the title and move the note into the right PARA/domain folder after inserting this template. -->

    ## Current understanding

    ## Evidence

    ## Tensions / caveats

    ## Open questions

    ## Related pages
  '';
in {
  # Create the standard Pi global resource directories.
  # The directories stay writable for Pi and manual experimentation; only the
  # placeholder files are managed declaratively.
  home.file.".pi/agent/extensions/.keep".text = "";
  home.file.".pi/agent/prompts/.keep".text = "";
  home.file.".pi/agent/skills/.keep".text = "";
  home.file.".pi/agent/themes/.keep".text = "";

  # Bundle global Pi extensions and skills.
  home.file.".pi/agent/extensions/pi-web-access".source = piWebAccessRoot;
  home.file.".pi/agent/extensions/llm-wiki".source = llmWikiRoot;
  home.file.".pi/agent/extensions/wg-admin".source = ./extensions/wg-admin;
  home.file.".pi/agent/skills/librarian/SKILL.md".source = "${piWebAccessRoot}/skills/librarian/SKILL.md";
  home.file.".pi/agent/skills/wg-admin/SKILL.md".source = ./skills/wg-admin/SKILL.md;

  # Put the shared llm-wiki in Sync so Syncthing keeps it aligned across hosts.
  home.sessionVariables.PI_LLM_WIKI_DIR = llmWikiDir;

  # Seed pi-web-access config once, then leave it mutable for Pi commands.
  home.activation.piWebAccessStarter = lib.hm.dag.entryAfter ["writeBoundary"] ''
    config_path="$HOME/.pi/web-search.json"
    if [ ! -e "$config_path" ]; then
      mkdir -p "$HOME/.pi"
      printf '%s\n' '${starterConfig}' > "$config_path"
    fi
  '';

  # Seed a tiny llm-wiki starter once, then leave it fully mutable.
  home.activation.llmWikiStarter = lib.hm.dag.entryAfter ["writeBoundary"] ''
    wiki_root='${llmWikiDir}'

    mkdir -p \
      "$wiki_root/pages/sources" \
      "$wiki_root/pages/projects/technical" \
      "$wiki_root/pages/projects/personal" \
      "$wiki_root/pages/areas/technical" \
      "$wiki_root/pages/areas/personal" \
      "$wiki_root/pages/resources/technical" \
      "$wiki_root/pages/resources/personal" \
      "$wiki_root/pages/archives" \
      "$wiki_root/pages/journal/daily" \
      "$wiki_root/pages/technical" \
      "$wiki_root/pages/personal" \
      "$wiki_root/raw" \
      "$wiki_root/meta" \
      "$wiki_root/templates/obsidian"

    [ -e "$wiki_root/README.md" ] || cp ${llmWikiReadme} "$wiki_root/README.md"
    [ -e "$wiki_root/WIKI_SCHEMA.md" ] || cp ${llmWikiSchema} "$wiki_root/WIKI_SCHEMA.md"
    [ -e "$wiki_root/pages/resources/technical/system-landscape.md" ] || cp ${llmWikiTechnicalStarter} "$wiki_root/pages/resources/technical/system-landscape.md"
    [ -e "$wiki_root/pages/resources/technical/pad-nixos.md" ] || cp ${llmWikiPadStarter} "$wiki_root/pages/resources/technical/pad-nixos.md"
    [ -e "$wiki_root/pages/areas/personal/personal-identity.md" ] || cp ${llmWikiPersonalStarter} "$wiki_root/pages/areas/personal/personal-identity.md"
    [ -e "$wiki_root/templates/obsidian/daily-journal.md" ] || cp ${llmWikiDailyJournalTemplate} "$wiki_root/templates/obsidian/daily-journal.md"
    [ -e "$wiki_root/templates/obsidian/page.md" ] || cp ${llmWikiPageTemplate} "$wiki_root/templates/obsidian/page.md"
  '';
}
